---

- name: "[DEBIAN (wheezy)] installing python-pip ..."
  apt:
    name: python-pip
    update_cache: yes
    cache_valid_time: 3600
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
  become: yes

- name: "[DEBIAN (wheezy)] installing resilio-sync prerequisites ..."
  pip:
    name: "{{ item }}"
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
  with_items:
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
  become: yes

- name: "[DEBIAN] installing resilio-sync prerequisites ..."
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - gnupg
  become: yes

- name: "[DEBIAN] adding resilio repository key ..."
  apt_key:
    url: https://linux-packages.resilio.com/resilio-sync/key.asc
    state: present
  become: yes

- name: "[DEBIAN] adding resilio repository ..."
  apt_repository:
    repo: deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
    state: present
    filename: 'resilio-sync'
  become: yes

- name: "[DEBIAN] updating aptitude cache ..."
  apt:
    update_cache: yes
  become: yes

- name: "[DEBIAN] installing resilio-sync ..."
  apt:
    name: resilio-sync
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: "[DEBIAN] enabling resilio-sync on startup ..."
  service:
    name: resilio-sync
    state: restarted
    enabled: yes
  become: yes

- name: "[DEBIAN] creating resilio folders ..."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: rslsync
    group: rslsync
  with_items: "{{ resilio_folders }}"
  become: yes
